### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by danixt1** [danixt1/Scheduler#6]
# 1.0 Version Goals

A system for scheduling events with customizable activation.

## Location
Location define the address to send the alert, and all data needed to send a basic location structure is:

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>name</td>
            <td>string</td>
            <td>The location name</td>
        </tr>
        <tr>
            <td>type</td>
            <td>Integer</td>
            <td>Location type to send, each number represent a data structure</td>
        </tr>
        <tr>
            <td>data</td>
            <td>JSON string</td>
            <td>Object with the data from the specified <b>type</b></td>
        </tr>
    </tbody>
</table>

### Http Request (type 1)

Storage data to start a HTTP request case return anything diff from 2XX is determine a failed sending.

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>u</td>
            <td>string</td>
            <td>Url to init the request</td>
        </tr>
        <tr>
            <td>m</td>
            <td>(GET | POST | DELETE | UPDATE)</td>
            <td>the method to make the request</td>
        </tr>
        <tr>
            <td>h</td>
            <td>JSON string</td>
            <td>Additional header to pass in request</td>
        </tr>
        <tr>
            <td>d</td>
            <td>(default | header | query | json)</td>
            <td>method to pass event data. the default method is <b>json</b></td>
        </tr>
    </tbody>
</table>

## Sender

Define a list of locations to send the trigged event,
 allow to define callbacks in case of failure sending to the mains locations.

Contains one or more [Locations](#location) to by sended on event fire, 
can contain a Location callback to by trigged on any location have failed the operation.

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>name</td>
            <td>string</td>
            <td>The name of sender</td>
        </tr>
        <tr>
            <td>locations</td>
            <td><a href="#location">Locations[]</a></td>
            <td>locations with refered sender</td>
        </tr>
        <tr>
            <td>fallbacks</td>
            <td><a href="#location">Locations[]</a></td>
            <td>Called on 1 or more main locations fail</td>
        </tr>
    </tbody>
</table>

## Calendar Event

Storage details from the events.

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>type</td>
            <td>integer</td>
            <td>The event type</td>
        </tr>
        <tr>
            <td>data</td>
            <td>JSON string</td>
            <td>locations with refered sender</td>
        </tr>
    </tbody>
</table>

### Reminder (type 1)

Reminder is a unique event, after trigged is deleted, your structure is:

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>name</td>
            <td>string</td>
            <td>Event name</td>
        </tr>
        <tr>
            <td>description</td>
            <td>string</td>
            <td>Description from the event</td>
        </tr>
    </tbody>
</table>

## Time events

trigger with details to a [Event](#events-data) by fired.

<table>
    <thead>
        <tr>
            <th>Property</th>
            <th>Type</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>sender</td>
            <td><a href="#location">Sender</a></td>
            <td>Linked sender in the event to fire the event</td>
        </tr>
        <tr>
            <td>data</td>
            <td><a href="#calendar-event">Calendar Event</a></td>
            <td>The Object data to by passed to locations</td>
        </tr>
        <tr>
            <td>date</td>
            <td>string</td>
            <td>the date in UTC time to fire the event with fire precision in minutes</td>
        </tr>
    </tbody>
</table>

# To do list

## BackEnd
- Models
    - [X] Sender
    - [X] Location
- [X] internal trigger to fire events
- [X] notifications (Unique calendar event)
- [X] [Sender system](#sender)
- [X] [location system](#location)
    - [X] HTTP location option

## FrontEnd
- API
    - [X] trigger event on edit
    - [X] trigger event on delete
- Form
    - Base Form System
        - [X] Support to show errors in input fields
        - [ ] #7
        - [ ] #8
    - [X] Form Sender
    - [X] Form Notification
    - [X] Form Location
        - [ ] Button to test if successfully trigger passed location.
- List System
    - [X] Delete item button
    - [X] Edit item button
    - [ ] Refresh on item deleted
    - [ ] Refresh on item edited
    - [ ] Make pagination system in list
- [X] month window
- [ ] weekly window
- [ ] event trigged alert
- [ ] route system to forms/windows
- [ ] dark/light theme
